server:
  port: 8082
spring:
  h2:
   console:
    enabled: true
    path: /h2-console    
  datasource:
   username: sa
   password: 
   url: jdbc:h2:~/test
   driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
   # hibernate:
    #  ddl-auto: create
app:
  name: Employee


